language: python

python:
  - "3.8"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.9
      install:
        - cd ./lab_2/
        - make install
      script: make test-cli