language: python

python:
  - "3.8"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.9
      install:
        - cd ./lab2/
        - make install
      script: make test-cli
      - stage: "Build Lab 3."
      name: "Run Djungo Server and test it."
      python: 3.9
      install:
        - cd ./lab3/
        - pipenv install
      script: ./travis.sh